const mongoose = require('mongoose');

const productsSchema = mongoose.Schema({
    _id			              : mongoose.Schema.Types.ObjectId,
    vendor_ID                 : { type: mongoose.Schema.Types.ObjectId, ref: 'entitymasters' },
    user_ID                   : { type: mongoose.Schema.Types.ObjectId, ref: 'users' },
    vendorName                : String,
    section                   : String,
    section_ID                : { type: mongoose.Schema.Types.ObjectId, ref: 'sections' },
    category                  : String,
    categoryNameRlang         : String,
    category_ID               : { type: mongoose.Schema.Types.ObjectId, ref: 'categories' },
    subCategory               : String,
    subCategoryUrl            : String,
    subCategory_ID            : { type: mongoose.Schema.Types.ObjectId, ref: 'categories' },
    brand                     : String,
    brandNameRlang            : String,
    universalProductCode      : String,
    productCode               : String,
    itemCode                  : String,
    productName               : String,
    productNameRlang          : String,
    productUrl                : String,
    productDetails            : String,
    shortDescription          : String,
    productReturnable         : String,
    featureList               : String,
    currency                  : String,
    size                      : String,
    color                     : String,
    tags                      : [],
    originalPrice             : Number,
    discountPercent           : Number,
    discountedPrice           : Number,    
    availableQuantity         : Number,
    productImage              : Array,
    productSmallImage         : Array,
    productVideo              : Array,
    productYTubeVideo         : String,
    productVideoType          : String,
    productPDF                : String,
    productBrochurePDF        : String,
    productInfoPDF            : String,
    status                    : String,
    featured                  : Boolean,
    exclusive                 : Boolean,
    newProduct                : Boolean,
    bestSeller                : Boolean,
    type                      : String,
    unit                      : String,
    vendorBarcode             : String,    
    vendorItemcode            : String,
    attributes                : [ 
        {
            index            : String,
            attributeName    : String,
            attributeValue   : String
        }
    ],
    taxId                    : { type: mongoose.Schema.Types.ObjectId, ref: 'expensetypemasters' },
    taxName                  : String,
    taxInclude               : Boolean,
    taxRate                  : Number,    
    fileName                 : String,
    createdBy                : String,
    createdAt                : Date,
    updatedBy                : String,
    updatedAt                : Date,
    isWish                   : Boolean
});

module.exports = mongoose.model('products',productsSchema);