const mongoose = require("mongoose");

const casestudy = mongoose.Schema({
  _id: mongoose.Schema.Types.ObjectId,
  user_id: { type: mongoose.Schema.Types.ObjectId, ref: "user" },
  projectName: String,
  service : String,
  projectDescription: String,
  pageURL:String,
  leftContent1:String,
  rightContent1: String,
  rightContent2: String,
  leftContent2:String,
  rightContent3: String,

  bannerImage : String,
  smallBannerImage : String,
  bannerImageRILC1 : String,
  smallBannerImageRILC1 : String,
  leftContent1 : String,
  rightImg1 : String,
  bannerImg2 : String,
  smallBannerImg2 : String,
  bannerImageLIRC1 : String,
  smallBannerImageLIRC1 : String,
  rightContent1 : String,
  leftImg1 : String,
  bannerImg3 : String,
  smallBannerImg3 : String,
  bannerImageLIRC2 : String,
  smallBannerImageLIRC2 : String,
  rightContent2 : String,
  leftImg2 : String,
  bannerImageRILC2 : String,
  smallBannerImageRILC2 : String,
  leftContent2 : String,
  rightImg2 : String,
  bannerImageLIRC3 : String,
  smallBannerImageLIRC3 : String,
  rightContent3 : String,
  leftImg4 : String,
  bannerImg4 : String,
  smallBannerImg4 : String,
  
  numOfWords: Number,
  readingInMin: Number,
  noOfVisited: Number,
  usersLiked: Array,
  createdBy: { type: mongoose.Schema.Types.ObjectId, ref: "user" },
  authorName: String,
  createdAt: Date,
  updatedAt: Date,
  approvalStatus: { type: String, default: "Approved" },
  approvalLog: [
    {
      status: String,
      updatedAt: Date,
      updatedBy: String,
      remark: String,
    },
  ],
});

module.exports = mongoose.model("casestudy", casestudy);
